# Generated by Django 4.0.3 on 2022-03-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VariantsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('KOD_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('KOD_year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TasksList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.variantslist')),
            ],
        ),
        migrations.CreateModel(
            name='EventTpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('file', models.TextField()),
                ('violation_level', models.CharField(max_length=100)),
                ('verdict', models.CharField(max_length=100)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.taskslist')),
            ],
        ),
        migrations.CreateModel(
            name='EventToTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.eventtpl')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tag')),
            ],
        ),
        migrations.CreateModel(
            name='EventToPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.eventtpl')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.policy')),
            ],
        ),
        migrations.CreateModel(
            name='EventToObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.eventtpl')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.object')),
            ],
        ),
    ]
